api_!login_check:
    path: /api/login_check

api:
    resource: "."
    type:     "api"
    prefix:   "/api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"
