annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  Person:
    properties:
      email: ~
      firstname: ~
      lastname: ~
      maidenname: ~
      username: ~
      birthdate: ~
      gender: ~
      address: ~
      city: ~
      zipcode: ~
      department: ~
      region: ~
      mobilephone: ~
      phone: ~
      profession: ~
      status: ~
  Responsability:
    properties:
      name: ~
