imports:
    # RESOURCES
    - { resource: services/encasement.yml }
    - { resource: services/encasement_detail.yml }
    - { resource: services/encasement_type.yml }
    - { resource: services/person.yml }
    - { resource: services/person_status.yml }
    - { resource: services/person_responsability.yml }
    - { resource: services/organ.yml }
    - { resource: services/organ_type.yml }
    - { resource: services/responsability.yml }
    - { resource: services/status.yml }

services:

    # Others
    fos_user.doctrine_registry:
        alias: doctrine