imports:
    # RESOURCES
    - { resource: services/order.yml }
    - { resource: services/payment.yml }
    - { resource: services/product.yml }
    - { resource: services/person.yml }
    - { resource: services/person_status.yml }
    - { resource: services/person_responsability.yml }
    - { resource: services/organ.yml }
    - { resource: services/organ_type.yml }
    - { resource: services/responsability.yml }
    - { resource: services/status.yml }
    - { resource: services/blog_posting.yml }
    - { resource: services/category.yml }
    - { resource: services/event.yml }
    - { resource: services/registration.yml }
    - { resource: services/election.yml }

services:

# JWT Creation Listener
    jwt_created_event_listener:
        class: AppBundle\EventListener\JWTCreatedListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

# Others
    fos_user.doctrine_registry:
        alias: doctrine

# Manager
    app.mailer:
        class: 'AppBundle\Manager\Mailer'
        arguments: [ '@mailer', '@templating', '%url%', '%mail_from%' ]
