services:

    # API resources
    resource.person:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\Person' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'person_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'person_write' ] } ]
        tags:      [ { name: 'api.resource' } ]

    # Others
    fos_user.doctrine_registry:
        alias: doctrine