services:
    resource.blog_posting:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\BlogPosting' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'blog_posting_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'blog_posting_write' ] } ]
        tags:      [ { name: 'api.resource' } ]


# My listeners
    blog_posting.event_listener:
        class: 'AppBundle\EventListener\BlogPostingEventListener'
        arguments: [ "@security.token_storage" ]
        tags:
          - { name: 'kernel.event_listener', event: 'api.pre_create_validation', method: 'onPreBlogPostingCreate' }