services:
    resource.event:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\Event' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'event_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'event_write' ] } ]
        tags:      [ { name: 'api.resource' } ]