services:

    resource.organ_type:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\OrganType' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'organ_type_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'organ_type_write' ] } ]
        tags:      [ { name: 'api.resource' } ]