services:
    resource.person:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\Person' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'person_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'person_write' ] } ]
          -         method: 'initFilters'
                    arguments:  [[ '@resource.person.search_filter', '@resource.person.order_filter', '@resource.person.gender_filter' ]]
        tags:      [ { name: 'api.resource' } ]

# My filters
    resource.person.search_filter:
        class: 'AppBundle\Filter\PersonSearchFilter'
        arguments:
            -   @doctrine

    resource.person.order_filter:
        class: 'AppBundle\Filter\PersonOrderFilter'
        arguments:
            -   @doctrine

    resource.person.gender_filter:
        class: 'AppBundle\Filter\PersonGenderFilter'
        arguments:
            -   @doctrine

# My listeners
    person.event_listener:
        class: 'AppBundle\EventListener\PersonEventListener'
        arguments: [ "%mail_from%", "@app.mailer", "@doctrine.orm.entity_manager" ]
        tags:
          - { name: 'kernel.event_listener', event: 'api.pre_create', method: 'onPrePersonCreate' }
          - { name: 'kernel.event_listener', event: 'api.pre_update', method: 'onPrePersonUpdate' }
          - { name: 'kernel.event_listener', event: 'api.post_update', method: 'onPostPersonUpdate' }