services:
    resource.registration:
        parent:    'api.resource'
        arguments: [ 'AppBundle\Entity\Registration' ]
        calls:
          -         method:    'initNormalizationContext'
                    arguments: [ { groups: [ 'registration_read' ] } ]
          -         method:    'initDenormalizationContext'
                    arguments: [ { groups: [ 'registration_write' ] } ]
        tags:      [ { name: 'api.resource' } ]

# My listeners
    registration.event_listener:
        class: 'AppBundle\EventListener\RegistrationEventListener'
        arguments: [ "@security.token_storage" ]
        tags:
          - { name: 'kernel.event_listener', event: 'api.pre_create_validation', method: 'onPreRegistrationCreate' }